#!/usr/bin/env python3
"""Port of the n64-decomp-workbench IDO 5.3 uopt CDX profile to IDO 7.1.

Input : build/7.1/uopt.c generated by decompals/ido-static-recomp at commit
        d5aec59932034b8a20f23f471297a55c45dcbc45 (see PINNED_SHA256).
Output: build/7.1-traced/uopt.gc.c plus one backup per stage, mirroring the
        stage layout of the original hand port:

    uopt.gc.c.bak_ichain   stage 1  globalcolor decisions/costs/forces only
    uopt.gc.c.bak_nodes    stage 2  + lineage (ICHAIN tables), symtab, temps
    uopt.gc.c.pre_cmdump   stage 3  + graph-node dump, incoming u-code dump
    uopt.gc.c              stage 4  + f_optinit code-motion dump hook

The record grammar and CDX_* switches are the workbench's (HEADER and the force
parser are imported from decomp_workbench.instrument_uopt so the reader and
the producer cannot drift).  Every 7.1 anchor and emulated address below was
re-derived from the 7.1 generated source; the derivation is recorded next to
each one.  Struct field offsets (liverange, ichain, graphnode, itable) are
carried over from the 5.3 profile and are *assumed* unchanged between 5.3 and
7.1; the positive controls in README-cdx71.md are what checks them.

Usage: python3 cdx71/patch_uopt71.py build/7.1/uopt.c build/7.1-traced
"""

from __future__ import annotations

import hashlib
import sys
from pathlib import Path

from decomp_workbench.instrument_uopt import HEADER, color_register_table

PINNED_SHA256 = "5da5580a14ca58a0d1dae94a4c0fcfdefc0e08b07469e9c8ccfd8d572db7e38f"  # build/7.1/uopt.c @ recomp d5aec599

# --- 7.1 emulated addresses (5.3 value -> 7.1 value, how established) -------
ADDR = {
    # f_globalcolor entry: t7 = MEM_U32(0x1001c530); t8 = MEM_U32(t7 + 52)
    # aligned 1:1 with 5.3's 0x10021c74 by difflib over the two bodies.
    "curproc": ("0x10021c74", "0x1001c530"),
    # globalcolor 'allcallersave' byte (v1 = MEM_U8(0x1001c4d0)) at the six
    # sites where 5.3 reads MEM_U8(0x1001eb70).
    "allcallersave": ("0x1001eb70", "0x1001c4d0"),
    # f_printitab loop: count t8 = MEM_U32(0x1001c390), base
    # t9 = MEM_U32(0x1001c3a0), stride 8 -- same shape as 5.3 0x1001cb38/cc30.
    "itab_count": ("0x1001cb38", "0x1001c390"),
    "itab_base": ("0x1001cc30", "0x1001c3a0"),
}
GRAPH_HEAD = "0x1001c358"   # f_printcm: s0 = MEM_U32(0x1001c358); s0 = MEM_U32(s0 + 12)
TEMP_HEAD = "0x1001c320"    # f_gettemp: list head; tail 0x1001c324; 20-byte records
FRAME_TEMPS = "0x1001c31c"  # f_gettemp: running temp-area size
ADDR_ITAB_COUNT = "0x1001c390"  # f_printitab: itable record count (newbit idx = count-1)
UTAB = "0x1001f300"         # f_readuinstr: 19-byte opcode descriptor table
DBUG_LEVEL = "0x1001c458"   # -zdbug:N value; f_main calls f_printcm iff == 3
LIST_OPEN = "0x1001c424"    # f_getoption: listing file already opened flag
LIST_FILE = "0x1001c6a0"    # Pascal text file f_printcm writes to
LIST_NAME = "0x1001df00"    # 1024-byte name buffer passed to f_rewrite


def replace_once(source: str, old: str, new: str, label: str) -> str:
    count = source.count(old)
    if count != 1:
        raise SystemExit(f"7.1 anchor {label!r} occurred {count} times")
    return source.replace(old, new, 1)


def header71() -> str:
    text = HEADER.replace("DKWB_CDX_COLOR_TABLE\n", color_register_table())
    text = text.replace(
        "Generated by n64-decomp-workbench for the pinned IDO 5.3 static-recomp\n * profile.",
        "Ported to IDO 7.1 by cdx71/patch_uopt71.py (from the workbench's 5.3\n * profile).",
    )
    old, new = ADDR["curproc"]
    assert text.count(f"MEM_U32({old})") == 1
    text = text.replace(f"MEM_U32({old})", f"MEM_U32({new})")
    # 7.1 reuses graphnode+308 for bit-vector headers by globalcolor time
    # (measured: every node read 2 there, while f_init_graphnode had stored
    # 3/5/5/5/5/5 for the microcase). Read the creation-time line instead.
    assert text.count("(int)MEM_U32(graphnode + 308)") == 2
    text = text.replace("(int)MEM_U32(graphnode + 308)", "dkwb_cdx_node_line(graphnode)")
    return text


NODE_LINE_MAP = r"""
/* ---- graph-node creation line (7.1) ----
 * f_init_graphnode stores the current Uloc line (MEM_U32(0x1001c404), set by
 * f_copyline from Uloc +4) at node+308, but 7.1 later overwrites that word.
 * The wrapper below records it host-side so records can report the line the
 * block was created on. Keyed by emulated node address; re-recorded when the
 * allocator reuses an address for a new procedure. */
#define DKWB_NODE_LINES 65536
static uint32_t dkwb_node_key[DKWB_NODE_LINES];
static int32_t dkwb_node_val[DKWB_NODE_LINES];
static void dkwb_cdx_node_line_record(uint32_t node, int32_t line) {
    uint32_t h = (node >> 3) & (DKWB_NODE_LINES - 1), i;
    for (i = 0; i < DKWB_NODE_LINES; i++, h = (h + 1) & (DKWB_NODE_LINES - 1))
        if (dkwb_node_key[h] == 0 || dkwb_node_key[h] == node) {
            dkwb_node_key[h] = node; dkwb_node_val[h] = line; return;
        }
}
static int dkwb_cdx_node_line(uint32_t node) {
    uint32_t h = (node >> 3) & (DKWB_NODE_LINES - 1), i;
    if (node == 0) return -1;
    for (i = 0; i < DKWB_NODE_LINES; i++, h = (h + 1) & (DKWB_NODE_LINES - 1)) {
        if (dkwb_node_key[h] == node) return (int)dkwb_node_val[h];
        if (dkwb_node_key[h] == 0) return -1;
    }
    return -1;
}
"""


def stage_node_lines(src: str) -> str:
    sig = "static void f_init_graphnode(uint8_t *mem, uint32_t sp, uint32_t a0) {\n"
    return replace_once(
        src, sig,
        NODE_LINE_MAP
        + sig.replace("f_init_graphnode", "f_init_graphnode_stock").replace(" {\n", ";\n")
        + sig
        + "    f_init_graphnode_stock(mem, sp, a0);\n"
        "    dkwb_cdx_node_line_record(a0, (int32_t)MEM_U32(a0 + 308));\n}\n"
        + sig.replace("f_init_graphnode", "f_init_graphnode_stock"),
        "init_graphnode wrapper",
    )


# ----------------------------------------------------------------- stage 1 ---
def stage_globalcolor(src: str) -> str:
    src = stage_node_lines(src)
    src = replace_once(
        src,
        "static void f_compute_save(uint8_t *mem, uint32_t sp, uint32_t a0) {\n",
        header71() + "\nstatic void f_compute_save(uint8_t *mem, uint32_t sp, uint32_t a0) {\n",
        "instrumentation header",
    )
    src = replace_once(
        src,
        "uint32_t a3 = 0;\nL469280:\n//globalcolor:",
        "uint32_t a3 = 0;\n"
        "int dkwb_cdx_ordinal;\nint dkwb_cdx_decision;\n"
        "dkwb_cdx_init();\ndkwb_cdx_procindex();\n"
        "dkwb_cdx_proc_decisions = 0;\ndkwb_cdx_globalcolor_ordinal++;\n"
        "dkwb_cdx_ordinal = dkwb_cdx_globalcolor_ordinal;\n"
        'DKWB_CDX_LOG(dkwb_cdx_ordinal, "[CDX] globalcolor proc=%d\\n", dkwb_cdx_ordinal);\n'
        "/*DKWB_GC_ENTRY_EXTRA*/\n"
        "L469280:\n//globalcolor:",
        "globalcolor entry",
    )
    src = replace_once(
        src,
        "L4698f0:\ns5 = MEM_U32(sp + 276);\nL4698f4:\nf0.w[0] = MEM_U32(s5 + 48);\n",
        "L4698f0:\ns5 = MEM_U32(sp + 276);\nL4698f4:\nf0.w[0] = MEM_U32(s5 + 48);\n"
        "DKWB_CDX_LOG(dkwb_cdx_ordinal, "
        '"[CDX] p1cand phase=p1 proc=%d web=%d sym=%d save=%.6f nocs=%d best=%.6f\\n", '
        "dkwb_cdx_ordinal, (int)MEM_U32(sp + 272), "
        "(int)MEM_U16(MEM_U32(s5 + 0) + 2), (double)f0.f[0], "
        "(int)MEM_U32(s5 + 28), (double)f20.f[0]);\n",
        "phase-one candidate",
    )
    for label, phase, kind, webslot in (
        ("L469a84", "p1", "caller", 268), ("L469c50", "p1", "callee", 268),
        ("L46a450", "p2", "caller", 272), ("L46a63c", "p2", "callee", 272),
    ):
        src = replace_once(
            src,
            f"{label}:\ncf = f2.f[0] < f20.f[0];",
            f"{label}:\n"
            f'DKWB_CDX_COST(dkwb_cdx_ordinal, "{phase}", (int)MEM_U32(sp + {webslot}), '
            f'(int)s2, "{kind}", f2.f[0], f20.f[0]);\n'
            "cf = f2.f[0] < f20.f[0];",
            f"{phase} {kind} cost",
        )

    def decision(phase, webslot, save, nocs, total, split_when_cf):
        acs = ADDR["allcallersave"][1]
        on_split, on_color = ("1", "0") if split_when_cf else ("0", "1")
        verdict = '"split" : "color"' if split_when_cf else '"color" : "no-color"'
        return (
            "{\n"
            f"    int dkwb_web = (int)MEM_U32(sp + {webslot});\n"
            "    dkwb_cdx_proc_decisions++;\n"
            f'    dkwb_cdx_decision = dkwb_cdx_force_color(dkwb_cdx_ordinal, "{phase}", "dec", dkwb_web,\n'
            "        MEM_U32(s5 + 40), MEM_U32(s5 + 44));\n"
            "    DKWB_CDX_LOG(dkwb_cdx_ordinal, "
            f'"[CDX] {phase}dec phase={phase} proc=%d web=%d sym=%d class=%d save=%.6f '
            "nocs=%d totalsave=%.6f bestcost=%.6f bestcolor=%d bestreg=%s "
            "forbidden0=0x%08x forbidden1=0x%08x regsleft=%d numintf=%d "
            "available0=0x%08x available1=0x%08x allcallersave=%d taken1=%d taken2=%d "
            'decision=%s forced=%d\\n", dkwb_cdx_ordinal, dkwb_web, '
            "(int)MEM_U16(MEM_U32(s5 + 0) + 2), (int)s6, "
            f"(double){save}.f[0], (int){nocs}, (double){total}.f[0], "
            "(double)f20.f[0], (int)MEM_U32(sp + 220), "
            "dkwb_cdx_register_name((int)MEM_U32(sp + 220)), "
            "(unsigned int)MEM_U32(s5 + 40), (unsigned int)MEM_U32(s5 + 44), "
            "(int)MEM_U8(s5 + 33), (int)MEM_U32(s5 + 36), "
            "(unsigned int)MEM_U32(sp + 212), (unsigned int)MEM_U32(sp + 216), "
            f"(int)MEM_U8({acs}), "
            "dkwb_cdx_reg_taken(mem, 1), dkwb_cdx_reg_taken(mem, 2), "
            f"cf ? {verdict}, dkwb_cdx_decision);\n"
            f'    dkwb_cdx_log_interference(mem, dkwb_cdx_ordinal, "{phase}", dkwb_web, s5);\n'
            f"    if (dkwb_cdx_decision == -1) cf = {on_split};\n"
            f"    else if (dkwb_cdx_decision >= 0) cf = {on_color};\n"
            "}\n"
        )

    # 7.1 keeps 5.3's registers at both decision sites (verified by reading
    # the preceding loads: save in f10/f8, nocs in t2/t0, total in f6/f10,
    # class in s6, range in s5).
    src = replace_once(
        src,
        "cf = f6.f[0] <= f20.f[0];\n//nop;\nif (!cf) {",
        "cf = f6.f[0] <= f20.f[0];\n" + decision("p1", 268, "f10", "t2", "f6", True)
        + "//nop;\nif (!cf) {",
        "phase-one decision",
    )
    src = replace_once(
        src,
        "cf = f20.f[0] < f10.f[0];\n//nop;\nif (!cf) {",
        "cf = f20.f[0] < f10.f[0];\n" + decision("p2", 272, "f8", "t0", "f10", False)
        + "//nop;\nif (!cf) {",
        "phase-two decision",
    )

    def color(phase, webslot, label, next_line, mirror):
        return (
            f"{label}:\n"
            "{\n"
            f"    int dkwb_web = (int)MEM_U32(sp + {webslot});\n"
            f'    int dkwb_force = dkwb_cdx_force_color(dkwb_cdx_ordinal, "{phase}", "color", dkwb_web,\n'
            "        MEM_U32(s5 + 40), MEM_U32(s5 + 44));\n"
            "    if (dkwb_force >= 0) {\n"
            "        MEM_U32(sp + 220) = (uint32_t)dkwb_force;\n"
            f"        {mirror} = (uint32_t)dkwb_force;\n"
            "    }\n"
            "    DKWB_CDX_LOG(dkwb_cdx_ordinal, "
            f'"[CDX] {phase}color phase={phase} proc=%d web=%d sym=%d color=%d reg=%s forced=%d\\n", '
            "dkwb_cdx_ordinal, dkwb_web, (int)MEM_U16(MEM_U32(s5 + 0) + 2), "
            "(int)MEM_U32(sp + 220), dkwb_cdx_register_name((int)MEM_U32(sp + 220)), dkwb_force);\n"
            "}\n"
            f"{next_line}"
        )

    # 5.3 L471d6c (t8 preloaded, t5 loaded after) == 7.1 L469e84;
    # 5.3 L4727d4 (t0 preloaded, t8 loaded after) == 7.1 L46a82c.
    src = replace_once(src, "L469e84:\nt5 = MEM_U32(sp + 220);",
                       color("p1", 268, "L469e84", "t5 = MEM_U32(sp + 220);", "t8"),
                       "phase-one color")
    src = replace_once(src, "L46a82c:\nt8 = MEM_U32(sp + 220);",
                       color("p2", 272, "L46a82c", "t8 = MEM_U32(sp + 220);", "t0"),
                       "phase-two color")
    return src


# ----------------------------------------------------------------- stage 2 ---
SYMTAB_TEMPS = r"""
/* ---- CDX_SYMTAB (ported from uopt-5.3-cdx-symtab.patch) ---- */
static int dkwb_cdx_flag(const char *name) {
    const char *v = getenv(name);
    return v != NULL && *v != '\0' && *v != '0';
}
static const char *dkwb_cdx_itab_kinds[9] = {
    "empty", "islda", "isconst", "isvar", "isop", "isilda", "issvar",
    "dumped", "isrconst"
};
static void dkwb_cdx_dump_symtab(uint8_t *mem, int ordinal) {
    uint32_t count, base, i;
    if (!dkwb_cdx_flag("CDX_SYMTAB") || !dkwb_cdx_active(ordinal)) return;
    count = MEM_U32(ITAB_COUNT);
    base = MEM_U32(ITAB_BASE);
    if (!dkwb_cdx_emulated_pointer(base) || count == 0 || count > 0x40000u) {
        fprintf(dkwb_cdx_output, "[CDX] symtabcount proc=%d n=%u base=0x%08x UNAVAILABLE\n",
            ordinal, (unsigned)count, (unsigned)base);
        return;
    }
    fprintf(dkwb_cdx_output, "[CDX] symtabcount proc=%d n=%u base=0x%08x\n",
        ordinal, (unsigned)count, (unsigned)base);
    for (i = 0; i < count; i++) {
        uint32_t rec = MEM_U32(base + i * 8);
        int kind;
        if (!dkwb_cdx_emulated_pointer(rec)) {
            fprintf(dkwb_cdx_output, "[CDX] symtab proc=%d idx=%u rec=0x%08x nil\n",
                ordinal, (unsigned)i, (unsigned)rec);
            continue;
        }
        kind = (int)MEM_U8(rec + 0);
        fprintf(dkwb_cdx_output,
            "[CDX] symtab proc=%d idx=%u kind=%d name=%s dtype=%d selfidx=%d "
            "bit=%d ver=%d off=%d tag=%d class=%d b23=%d b24=%d vreg=%d "
            "op=%d l=%d r=%d raw08=0x%08x raw12=0x%08x raw16=0x%08x raw20=0x%08x "
            "raw24=0x%08x raw28=0x%08x raw32=0x%08x raw36=0x%08x rec=0x%08x\n",
            ordinal, (unsigned)i, kind,
            (kind >= 0 && kind < 9) ? dkwb_cdx_itab_kinds[kind] : "?",
            (int)MEM_U8(rec + 1), (int)MEM_U16(rec + 2),
            (int)MEM_U16(rec + 4), (int)MEM_U16(rec + 6),
            (int)MEM_U32(rec + 16), (int)MEM_U16(rec + 20),
            (int)MEM_U8(rec + 22), (int)MEM_U8(rec + 23),
            (int)MEM_U8(rec + 24), (int)MEM_U8(rec + 25),
            (int)MEM_U8(rec + 16),
            dkwb_cdx_emulated_pointer(MEM_U32(rec + 20)) ? (int)MEM_U16(MEM_U32(rec + 20) + 2) : -1,
            dkwb_cdx_emulated_pointer(MEM_U32(rec + 24)) ? (int)MEM_U16(MEM_U32(rec + 24) + 2) : -1,
            (unsigned)MEM_U32(rec + 8), (unsigned)MEM_U32(rec + 12),
            (unsigned)MEM_U32(rec + 16), (unsigned)MEM_U32(rec + 20),
            (unsigned)MEM_U32(rec + 24), (unsigned)MEM_U32(rec + 28),
            (unsigned)MEM_U32(rec + 32), (unsigned)MEM_U32(rec + 36),
            (unsigned)rec);
    }
}
/* ---- CDX_TEMPS: spill/stack temps handed out by f_gettemp ----
 * Record (20 bytes, read from f_gettemp): +0 temp number, +4 frame offset,
 * +8 size, +12 u8 free flag (0 = in use), +16 next.  List head TEMP_HEAD,
 * running temp-area size FRAME_TEMPS. */
static int dkwb_cdx_temps_seq;
static void dkwb_cdx_log_gettemp(uint8_t *mem, uint32_t out, uint32_t size) {
    uint32_t rec;
    dkwb_cdx_init();
    if (!dkwb_cdx_flag("CDX_TEMPS") || !dkwb_cdx_active(dkwb_cdx_globalcolor_ordinal)) return;
    rec = dkwb_cdx_emulated_pointer(out) ? MEM_U32(out) : 0;
    if (!dkwb_cdx_emulated_pointer(rec)) return;
    fprintf(dkwb_cdx_output,
        "[CDX] temp proc=%d seq=%d size=%u num=%d offset=%d tsize=%d area=%d rec=0x%08x\n",
        dkwb_cdx_globalcolor_ordinal, dkwb_cdx_temps_seq++, (unsigned)size,
        (int)MEM_U32(rec + 0), (int)MEM_U32(rec + 4), (int)MEM_U32(rec + 8),
        (int)MEM_U32(TEMP_AREA), (unsigned)rec);
}
static void dkwb_cdx_dump_temps(uint8_t *mem, int ordinal, const char *when) {
    uint32_t rec;
    int n = 0;
    if (!dkwb_cdx_flag("CDX_TEMPS") || !dkwb_cdx_active(ordinal)) return;
    for (rec = MEM_U32(TEMP_HEAD); dkwb_cdx_emulated_pointer(rec) && n < 100000;
            rec = MEM_U32(rec + 16), n++)
        fprintf(dkwb_cdx_output,
            "[CDX] templist proc=%d when=%s idx=%d num=%d offset=%d size=%d free=%d\n",
            ordinal, when, n, (int)MEM_U32(rec + 0), (int)MEM_U32(rec + 4),
            (int)MEM_U32(rec + 8), (int)MEM_U8(rec + 12));
    fprintf(dkwb_cdx_output, "[CDX] templistcount proc=%d when=%s n=%d area=%d\n",
        ordinal, when, n, (int)MEM_U32(TEMP_AREA));
}
"""


def stage_lineage_symtab_temps(src: str) -> str:
    src = replace_once(
        src,
        "static void f_formlivbb(uint8_t *mem, uint32_t sp, uint32_t a0, uint32_t a1, uint32_t a2) {\n",
        "static void dkwb_cdx_lineage_begin(void);\n"
        "static void dkwb_cdx_log_lineage_range(uint8_t *mem, uint32_t ichain, uint32_t liverange);\n"
        "static void dkwb_cdx_log_lineage_member(uint8_t *mem, uint32_t ichain, uint32_t graphnode, uint32_t liveblock);\n\n"
        "static void f_formlivbb(uint8_t *mem, uint32_t sp, uint32_t a0, uint32_t a1, uint32_t a2) {\n",
        "lineage declarations",
    )
    # 5.3 'MEM_U32(v0+56)=zero; goto L464644;' == 7.1 '... goto L45de54;'
    src = replace_once(
        src,
        "MEM_U32(v0 + 52) = zero;\nMEM_U32(v0 + 56) = zero;\ngoto L45de54;",
        "MEM_U32(v0 + 52) = zero;\nMEM_U32(v0 + 56) = zero;\n"
        "dkwb_cdx_log_lineage_range(mem, s0, v0);\ngoto L45de54;",
        "lineage range creation",
    )
    # 5.3 'L4647b8:\n// bdead 1 ra = ...' == 7.1 'L45df98:' (formlivbb epilogue)
    src = replace_once(
        src,
        "L45df98:\n// bdead 1 ra = MEM_U32(sp + 36);",
        "L45df98:\ndkwb_cdx_log_lineage_member(mem, s0, MEM_U32(sp + 92), MEM_U32(s1 + 0));\n"
        "// bdead 1 ra = MEM_U32(sp + 36);",
        "lineage member creation",
    )
    src = replace_once(src, "//makelivranges:\n",
                       "//makelivranges:\ndkwb_cdx_lineage_begin();\n", "lineage procedure entry")
    extra = (SYMTAB_TEMPS.replace("ITAB_COUNT", ADDR["itab_count"][1])
             .replace("ITAB_BASE", ADDR["itab_base"][1])
             .replace("TEMP_HEAD", TEMP_HEAD).replace("TEMP_AREA", FRAME_TEMPS))
    src = replace_once(
        src,
        "\nstatic void f_compute_save(uint8_t *mem, uint32_t sp, uint32_t a0) {\n",
        extra + "\nstatic void f_compute_save(uint8_t *mem, uint32_t sp, uint32_t a0) {\n",
        "symtab/temps helpers",
    )
    src = replace_once(src, "/*DKWB_GC_ENTRY_EXTRA*/\n",
                       "dkwb_cdx_dump_symtab(mem, dkwb_cdx_ordinal);\n"
                       'dkwb_cdx_dump_temps(mem, dkwb_cdx_ordinal, "globalcolor");\n'
                       "/*DKWB_GC_ENTRY_EXTRA*/\n", "symtab/temps at globalcolor")
    # wrap f_gettemp(a0 = out pointer, a1 = size)
    src = replace_once(
        src,
        "static void f_gettemp(uint8_t *mem, uint32_t sp, uint32_t a0, uint32_t a1) {\n",
        "static void f_gettemp_stock(uint8_t *mem, uint32_t sp, uint32_t a0, uint32_t a1);\n"
        "static void f_gettemp(uint8_t *mem, uint32_t sp, uint32_t a0, uint32_t a1) {\n"
        "    f_gettemp_stock(mem, sp, a0, a1);\n"
        "    dkwb_cdx_log_gettemp(mem, a0, a1);\n"
        "}\n"
        "static void f_gettemp_stock(uint8_t *mem, uint32_t sp, uint32_t a0, uint32_t a1) {\n",
        "gettemp wrapper",
    )
    return src


# ----------------------------------------------------------------- stage 3 ---
NODES_UCODE = r"""
/* ---- CDX_NODES: basic-block graph nodes (list walked like f_printcm) ----
 * head GRAPH_HEAD, next at +12, block number u16 at +8. line = the Uloc
 * line current when f_init_graphnode created the node (see node-line map).
 * Raw words are printed so nothing is lost if a named field is wrong. */
static void dkwb_cdx_dump_nodes(uint8_t *mem, int ordinal) {
    uint32_t node;
    int n = 0;
    if (!dkwb_cdx_flag("CDX_NODES") || !dkwb_cdx_active(ordinal)) return;
    for (node = MEM_U32(GRAPH_HEAD); dkwb_cdx_emulated_pointer(node) && n < 100000;
            node = MEM_U32(node + 12), n++) {
        fprintf(dkwb_cdx_output,
            "[CDX] node proc=%d idx=%d bb=%d line=%d raw00=0x%08x raw04=0x%08x "
            "raw16=0x%08x raw20=0x%08x raw24=0x%08x raw28=0x%08x node=0x%08x\n",
            ordinal, n, (int)MEM_U16(node + 8), dkwb_cdx_node_line(node),
            (unsigned)MEM_U32(node + 0), (unsigned)MEM_U32(node + 4),
            (unsigned)MEM_U32(node + 16), (unsigned)MEM_U32(node + 20),
            (unsigned)MEM_U32(node + 24), (unsigned)MEM_U32(node + 28),
            (unsigned)node);
    }
    fprintf(dkwb_cdx_output, "[CDX] nodecount proc=%d n=%d\n", ordinal, n);
}
/* ---- CDX_UCODE: every u-code instruction uopt reads (f_readuinstr) ----
 * Not filtered by CDX_PROC: u-code is read before that procedure's
 * globalcolor ordinal exists. The reader buffer is reused, so words a given
 * opcode does not set still hold the previous record's values. Measured on
 * 7.1: op 0x51 (81) is Uloc (f_copyline: file = u16 +2, line = w1). Every
 * record is read twice per run (prepass + main pass); see README. */
static int dkwb_cdx_ucode_seq;
static void dkwb_cdx_log_ucode(uint8_t *mem, uint32_t rec) {
    int op;
    if (!dkwb_cdx_flag("CDX_UCODE") || !dkwb_cdx_emulated_pointer(rec)) return;
    dkwb_cdx_init();
    op = (int)MEM_U8(rec + 0);
    fprintf(dkwb_cdx_output,
        "[CDX] ucode seq=%d op=%d w0=0x%08x w1=0x%08x w2=0x%08x w3=0x%08x "
        "w4=0x%08x w5=0x%08x w6=0x%08x w7=0x%08x\n",
        dkwb_cdx_ucode_seq++, op,
        (unsigned)MEM_U32(rec + 0), (unsigned)MEM_U32(rec + 4),
        (unsigned)MEM_U32(rec + 8), (unsigned)MEM_U32(rec + 12),
        (unsigned)MEM_U32(rec + 16), (unsigned)MEM_U32(rec + 20),
        (unsigned)MEM_U32(rec + 24), (unsigned)MEM_U32(rec + 28));
}
"""


def stage_nodes_ucode(src: str) -> str:
    extra = NODES_UCODE.replace("GRAPH_HEAD", GRAPH_HEAD).replace("UTAB", UTAB)
    src = replace_once(
        src,
        "\nstatic void f_compute_save(uint8_t *mem, uint32_t sp, uint32_t a0) {\n",
        extra + "\nstatic void f_compute_save(uint8_t *mem, uint32_t sp, uint32_t a0) {\n",
        "nodes/ucode helpers",
    )
    src = replace_once(src, "/*DKWB_GC_ENTRY_EXTRA*/\n",
                       "dkwb_cdx_dump_nodes(mem, dkwb_cdx_ordinal);\n/*DKWB_GC_ENTRY_EXTRA*/\n",
                       "nodes at globalcolor")
    sig = "static void f_readuinstr(uint8_t *mem, uint32_t sp, uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3) {\n"
    src = replace_once(
        src, sig,
        sig.replace("f_readuinstr", "f_readuinstr_stock").replace(" {\n", ";\n")
        + sig
        + "    f_readuinstr_stock(mem, sp, a0, a1, a2, a3);\n"
        "    dkwb_cdx_log_ucode(mem, a0);\n}\n"
        + sig.replace("f_readuinstr", "f_readuinstr_stock"),
        "readuinstr wrapper",
    )
    return src


# ----------------------------------------------------------------- stage 4 ---
CMDUMP = r"""
/* ---- CDX_CMDUMP / CDX_CMFILE: switch on uopt's own code-motion dump ----
 * f_main calls f_printcm after f_codemotion iff the -zdbug level
 * (DBUG_LEVEL) is 3, writing to the listing file LIST_FILE. f_getoption
 * opens that file with f_rewrite(LIST_FILE, LIST_NAME, 0x400, 0) and sets
 * LIST_OPEN. This hook, run right after f_processargs, does the same thing
 * the -Wo,-zdbug:3 option would, unless the user already passed -zdbug. */
static void dkwb_cdx_cmdump_hook(uint8_t *mem, uint32_t sp) {
    const char *v = getenv("CDX_CMDUMP");
    const char *name;
    uint32_t i, n;
    if (v == NULL || *v == '\0' || *v == '0') return;
    if (MEM_U32(DBUG_LEVEL) != 0) {
        fprintf(stderr, "DKWB: CDX_CMDUMP ignored: -zdbug:%u already set\n",
            (unsigned)MEM_U32(DBUG_LEVEL));
        return;
    }
    /* "1" keeps the original meaning (level 3 = f_printcm); any other number is
     * used as the -zdbug level directly: 1 printtab before copyprop, 7 after,
     * 2 printlinfo, 5 printregs, 4 printscm, 25 printprecm. */
    MEM_U32(DBUG_LEVEL) = (strcmp(v, "1") == 0) ? 3u : (uint32_t)atoi(v);
    if (MEM_U8(LIST_OPEN) != 0) return;
    name = getenv("CDX_CMFILE");
    if (name == NULL || *name == '\0') name = "uoptlist";
    n = (uint32_t)strlen(name);
    if (n > 0x3ff) n = 0x3ff;
    for (i = 0; i < 0x400; i++) MEM_U8(LIST_NAME + i) = (uint8_t)(i < n ? name[i] : ' ');
    f_rewrite(mem, sp, LIST_FILE, LIST_NAME, 0x400, 0);
    MEM_U8(LIST_OPEN) = 1;
}
"""


def stage_cmdump(src: str) -> str:
    body = (CMDUMP.replace("DBUG_LEVEL", DBUG_LEVEL).replace("LIST_OPEN", LIST_OPEN)
            .replace("LIST_FILE", LIST_FILE).replace("LIST_NAME", LIST_NAME))
    src = replace_once(
        src,
        "static void f_optinit(uint8_t *mem, uint32_t sp) {\n",
        "#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n" + body
        + "\nstatic void f_optinit(uint8_t *mem, uint32_t sp) {\n",
        "cmdump helper",
    )
    # f_optinit: 'f_processargs(mem, sp);\ngoto L438da4;' then 'L438da4:'
    src = replace_once(src, "L438da4:\n", "L438da4:\ndkwb_cdx_cmdump_hook(mem, sp);\n",
                       "cmdump hook after f_processargs")
    return src


# ----------------------------------------------------------------- stage 5 ---
# Copy-propagation / statement-fold / spill-slot / itable-creation tracing, ported
# from the 2026-10-07/08 pokestadium sessions (func_8430506C, func_84367660).
EXTRA_FWD = r"""
/* ---- stage-5 forward declarations (helpers are defined further down) ---- */
static FILE *dkwb_cdx_output;
static int dkwb_cdx_globalcolor_ordinal;
static void dkwb_cdx_init(void);
static int dkwb_cdx_active(int ordinal);
static int dkwb_cdx_emulated_pointer(uint32_t value);
static int dkwb_s5_flag(const char *name) {
    const char *v = getenv(name);
    return v != NULL && *v != '\0' && *v != '0';
}
/* CDX_CP=1 [CDX_CP_PROC=n]: copy propagation. n counts f_copypropagate calls
 * (one per procedure that reaches it; matches the globalcolor ordinal when every
 * procedure is optimized). */
static int dkwb_cp_proc = -1;
static int dkwb_cp_on(void) {
    static int ready = 0, on = 0, want = -1;
    if (!ready) {
        const char *v = getenv("CDX_CP_PROC");
        on = dkwb_s5_flag("CDX_CP");
        want = (v != NULL && *v != '\0') ? atoi(v) : -1;
        ready = 1;
    }
    return on && (want < 0 || want == dkwb_cp_proc);
}
static void dkwb_cp_node(uint8_t *mem, const char *tag, uint32_t p) {
    int i;
    if (!dkwb_cdx_emulated_pointer(p) || !dkwb_cdx_emulated_pointer(p + 31)) return;
    fprintf(stderr, "[CP]   %s@0x%08x:", tag, (unsigned)p);
    for (i = 0; i < 8; i++) fprintf(stderr, " %08x", (unsigned)MEM_U32(p + 4 * i));
    fprintf(stderr, "\n");
}
"""

CP_WRAPPERS = r"""
/* ---- CDX_CP wrappers ---- */
static void f_copypropagate(uint8_t *mem, uint32_t sp) {
    dkwb_cp_proc++;
    if (dkwb_cp_on()) fprintf(stderr, "[CP] begin proc=%d\n", dkwb_cp_proc);
    f_copypropagate_real(mem, sp);
    if (dkwb_cp_on()) fprintf(stderr, "[CP] end proc=%d\n", dkwb_cp_proc);
}
static void f_exprdelete(uint8_t *mem, uint32_t sp, uint32_t a0, uint32_t a1) {
    if (dkwb_cp_on()) {
        fprintf(stderr, "[CP] f_exprdelete a0=0x%08x a1=0x%08x\n", (unsigned)a0, (unsigned)a1);
        dkwb_cp_node(mem, "a0", a0);
        dkwb_cp_node(mem, "a1", a1);
    }
    f_exprdelete_real(mem, sp, a0, a1);
}
static uint32_t f_searchstore(uint8_t *mem, uint32_t sp, uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3) {
    uint32_t r = f_searchstore_real(mem, sp, a0, a1, a2, a3);
    if (dkwb_cp_on()) {
        fprintf(stderr, "[CP] f_searchstore a0=0x%08x a1=0x%08x a2=0x%08x a3=0x%08x -> 0x%08x\n",
            (unsigned)a0, (unsigned)a1, (unsigned)a2, (unsigned)a3, (unsigned)r);
        dkwb_cp_node(mem, "a2", a2);
        dkwb_cp_node(mem, "a3", a3);
    }
    return r;
}
static void f_istrfold(uint8_t *mem, uint32_t sp, uint32_t a0) {
    if (dkwb_cp_on()) {
        fprintf(stderr, "[CP] f_istrfold a0=0x%08x\n", (unsigned)a0);
        dkwb_cp_node(mem, "a0", a0);
    }
    f_istrfold_real(mem, sp, a0);
}
/* ---- CDX_NEWBIT=1: every itable record creation (f_newbit), tagged by caller ---- */
static uint32_t f_newbit(uint8_t *mem, uint32_t sp, uint32_t a0, uint32_t a1) {
    uint32_t r = f_newbit_real(mem, sp, a0, a1);
    if (dkwb_s5_flag("CDX_NEWBIT")) {
        uint32_t idx = MEM_U32(ITAB_COUNT) - 1, rec = a0;
        uint32_t l = MEM_U32(rec + 20), rr = MEM_U32(rec + 24);
        dkwb_cdx_init();
        fprintf(dkwb_cdx_output,
            "[CDX] newbit tagproc=%d idx=%u kind=%d dtype=%d op=%d l=%d r=%d a1=%u\n",
            dkwb_cdx_globalcolor_ordinal, (unsigned)idx, (int)MEM_U8(rec), (int)MEM_U8(rec + 1),
            (int)MEM_U8(rec + 16),
            dkwb_cdx_emulated_pointer(l) ? (int)MEM_U16(l + 2) : -1,
            dkwb_cdx_emulated_pointer(rr) ? (int)MEM_U16(rr + 2) : -1, (unsigned)a1);
    }
    return r;
}
"""

# f_constarith (called while uopt reads u-code, func_456310): every istr statement
# reaching the istrfold check, with its address operand's kind / mtype byte.
CA_CONSTARITH = (
    'if (dkwb_s5_flag("CDX_CA")) { uint32_t dkwb_ad = MEM_U32(s0 + 4);\n'
    ' if (v1 == 0x3f) fprintf(stderr, "[CA] istr s0=0x%08x w=%08x %08x %08x %08x %08x | adr kind=%u b50=%u w48=%08x b32=%u | flag4e0=%u\\n",\n'
    ' (unsigned)s0, (unsigned)MEM_U32(s0), (unsigned)MEM_U32(s0 + 4), (unsigned)MEM_U32(s0 + 8), (unsigned)MEM_U32(s0 + 12), (unsigned)MEM_U32(s0 + 16),\n'
    ' dkwb_cdx_emulated_pointer(dkwb_ad) ? (unsigned)MEM_U8(dkwb_ad) : 0u, dkwb_cdx_emulated_pointer(dkwb_ad) ? (unsigned)MEM_U8(dkwb_ad + 50) : 0u,\n'
    ' dkwb_cdx_emulated_pointer(dkwb_ad) ? (unsigned)MEM_U32(dkwb_ad + 48) : 0u, dkwb_cdx_emulated_pointer(dkwb_ad) ? (unsigned)MEM_U8(dkwb_ad + 32) : 0u,\n'
    ' (unsigned)MEM_U8(0x1001c4e0));\n'
    ' else fprintf(stderr, "[CA] stmt op=0x%02x s0=0x%08x\\n", (unsigned)v1, (unsigned)s0); }\n'
)
# f_copypropagate L417d14: a statement whose operands copyprop rewrote (s3/s6 = new
# address/value expressions) reaching the istr -> str fold (f_istrfold).
CA_COPYPROP = (
    'if (dkwb_s5_flag("CDX_CA")) fprintf(stderr, "[CA] cp-stmt s2=0x%08x w=%08x %08x %08x %08x %08x s3=0x%08x(k%u) s6=0x%08x(k%u)\\n",\n'
    ' (unsigned)s2, (unsigned)MEM_U32(s2), (unsigned)MEM_U32(s2 + 4), (unsigned)MEM_U32(s2 + 8), (unsigned)MEM_U32(s2 + 12), (unsigned)MEM_U32(s2 + 16),\n'
    ' (unsigned)s3, s3 ? (unsigned)MEM_U8(s3) : 0u, (unsigned)s6, s6 ? (unsigned)MEM_U8(s6) : 0u);\n'
)
# f_spilltemps L466438: each spilled item (a2 = itable record; kind 4 = expression)
# and the slot s5 it was given. Printed under the *previous* globalcolor ordinal.
SPILLTEMP = (
    'if (dkwb_s5_flag("CDX_TEMPS")) { dkwb_cdx_init(); if (dkwb_cdx_active(dkwb_cdx_globalcolor_ordinal))\n'
    ' fprintf(dkwb_cdx_output, "[CDX] spilltemp proc=%d rec=0x%08x kind=%d slot=%d w0=%08x w1=%08x w2=%08x w3=%08x w4=%08x w5=%08x w6=%08x w7=%08x\\n",\n'
    ' dkwb_cdx_globalcolor_ordinal, (unsigned)a2, (int)MEM_U8(a2), (int)s5, (unsigned)MEM_U32(a2), (unsigned)MEM_U32(a2 + 4),\n'
    ' (unsigned)MEM_U32(a2 + 8), (unsigned)MEM_U32(a2 + 12), (unsigned)MEM_U32(a2 + 16), (unsigned)MEM_U32(a2 + 20),\n'
    ' (unsigned)MEM_U32(a2 + 24), (unsigned)MEM_U32(a2 + 28)); }\n'
)


EMU_OLD = """static int dkwb_cdx_emulated_pointer(uint32_t value) {
    return value >= 0x10000000U && value < 0x20000000U;
}"""
EMU_NEW = """uint32_t dkwb_cdx_cur_sbrk(void);  /* cdx71/libc_impl_cdx71.c */
static int dkwb_cdx_emulated_pointer(uint32_t value) {
    /* range check alone is not enough: stale fields (e.g. ichain+8 of a freshly split
     * live range) point above the current break, where the region is still PROT_NONE
     * (SIGBUS on battle_engine_356730.c / battle_engine_2EC3C0.c with all logs on). */
    return value >= 0x10000000U && value < dkwb_cdx_cur_sbrk();
}"""


def stage_cp_ca_spill(src: str) -> str:
    src = replace_once(src, EMU_OLD, EMU_NEW, "break-aware emulated pointer check")
    src = replace_once(src, '#include "header.h"\n', '#include "header.h"\n#include <stdio.h>\n#include <stdlib.h>\n' + EXTRA_FWD,
                       "stage-5 forward declarations")
    for ret, name, args in [("void", "f_copypropagate", "uint8_t *mem, uint32_t sp"),
                            ("void", "f_exprdelete", "uint8_t *mem, uint32_t sp, uint32_t a0, uint32_t a1"),
                            ("uint32_t", "f_searchstore", "uint8_t *mem, uint32_t sp, uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3"),
                            ("void", "f_istrfold", "uint8_t *mem, uint32_t sp, uint32_t a0"),
                            ("uint32_t", "f_newbit", "uint8_t *mem, uint32_t sp, uint32_t a0, uint32_t a1")]:
        decl = "static %s %s(%s);\n" % (ret, name, args)
        src = replace_once(src, decl, decl + "static %s %s_real(%s);\n" % (ret, name, args), name + " decl")
        src = replace_once(src, "static %s %s(%s) {\n" % (ret, name, args),
                           "static %s %s_real(%s) {\n" % (ret, name, args), name + " def")
    src = src + CP_WRAPPERS.replace("ITAB_COUNT", ADDR_ITAB_COUNT)
    src = replace_once(src, "L452fc4:\n", "L452fc4:\n" + CA_CONSTARITH, "constarith istr check")
    src = replace_once(src, "L417d14:\n", "L417d14:\n" + CA_COPYPROP, "copyprop fold path")
    src = replace_once(src, "L466438:\n", "L466438:\n" + SPILLTEMP, "spilltemps slot")
    return src


def main() -> None:
    source_path, out_dir = Path(sys.argv[1]), Path(sys.argv[2])
    out_dir.mkdir(parents=True, exist_ok=True)
    src = source_path.read_text()
    digest = hashlib.sha256(src.encode()).hexdigest()
    print(f"input {source_path} sha256={digest}")
    if PINNED_SHA256 and digest != PINNED_SHA256:
        raise SystemExit("input is not the pinned 7.1 uopt.c; re-derive anchors first")
    stages = [
        ("uopt.gc.c.bak_ichain", stage_globalcolor),
        ("uopt.gc.c.bak_nodes", stage_lineage_symtab_temps),
        ("uopt.gc.c.pre_cmdump", stage_nodes_ucode),
        ("uopt.gc.c.pre_cpca", stage_cmdump),
        ("uopt.gc.c", stage_cp_ca_spill),
    ]
    for name, fn in stages:
        src = fn(src)
        (out_dir / name).write_text(src)
        print(f"wrote {out_dir / name} sha256={hashlib.sha256(src.encode()).hexdigest()}")


if __name__ == "__main__":
    main()
