#!/usr/bin/env python3
"""Render the public Stadium 1 coverage snapshot from tracked source."""

from __future__ import annotations

import argparse
import re
import subprocess
from pathlib import Path

BASELINE_TOTAL = 7_437
PRAGMA_RE = re.compile(r'GLOBAL_ASM\("asm/us/nonmatchings/[^" ]+/([^"/]+)\.s"\)')
START_MARKER = "<!-- AUTO_COVERAGE:START -->"
END_MARKER = "<!-- AUTO_COVERAGE:END -->"
GENERATED_HEADER = "<!-- Generated by ci/update_coverage.py. Do not edit by hand. -->"


def owners_by_file(repo_root: Path) -> dict[str, int]:
    result = subprocess.run(
        [
            "git", "-c", f"safe.directory={repo_root.as_posix()}", "-C", str(repo_root),
            "grep", "--no-color", "-E",
            r'GLOBAL_ASM\("asm/us/nonmatchings/[^" ]+/[^"/]+\.s"\)', "--", "src",
        ],
        capture_output=True, text=True, check=False,
    )
    if result.returncode not in (0, 1):
        raise RuntimeError(result.stderr.strip() or f"git grep failed: {result.returncode}")

    owners: dict[str, set[str]] = {}
    for line in result.stdout.splitlines():
        path, separator, content = line.partition(":")
        if not separator:
            continue
        match = PRAGMA_RE.search(content)
        if match:
            owners.setdefault(path, set()).add(match.group(1))
    return {path: len(names) for path, names in owners.items()}


def render(remaining_by_file: dict[str, int]) -> str:
    remaining = sum(remaining_by_file.values())
    covered = max(BASELINE_TOTAL - remaining, 0)
    percentage = covered / BASELINE_TOTAL * 100.0
    lines = [
        GENERATED_HEADER, "", "# pokestadium decompilation coverage", "", START_MARKER,
        f"- Functions with C implementations: **{covered:,} / {BASELINE_TOTAL:,} ({percentage:.1f}%)**",
        f"- Remaining `GLOBAL_ASM` owners: **{remaining:,}** (across {len(remaining_by_file)} source files)",
        END_MARKER, "",
        "The denominator is the 7,437-function public Stadium 1 snapshot. Regenerate with:",
        "`python3 ci/update_coverage.py`", "", "## Remaining owners by source file", "",
        "| File | Remaining owners |", "| --- | ---: |",
    ]
    for path in sorted(remaining_by_file):
        lines.append(f"| `{path}` | {remaining_by_file[path]:,} |")
    if not remaining_by_file:
        lines.append("_No source files with remaining `GLOBAL_ASM` owners._")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=None)
    parser.add_argument("--output", type=Path, default=None)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    repo_root = (args.repo_root or Path(__file__).resolve().parent.parent).resolve()
    output = (args.output or repo_root / "COVERAGE.md").resolve()
    generated = render(owners_by_file(repo_root))
    existing = output.read_text(encoding="utf-8") if output.exists() else None

    if args.check:
        if existing == generated:
            print(f"coverage: current ({output})")
            return 0
        print(f"coverage: stale ({output})")
        return 1

    if existing != generated:
        output.write_text(generated, encoding="utf-8")
        print(f"coverage: updated {output}")
    else:
        print(f"coverage: unchanged {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
