#!/usr/bin/env python3
"""Refresh Stadium 1 coverage from tracked GLOBAL_ASM pragmas.

The total function count is the retail-map value recorded in COVERAGE.md; this
script never executes PR code or requires a ROM.
"""
import argparse
import re
from pathlib import Path

PRAGMA = re.compile(r'#pragma GLOBAL_ASM\("asm/us/nonmatchings/[^" ]+/([A-Za-z_]\w*)\.s"\)')
TOTAL = re.compile(r'\*\*[0-9,]+ / ([0-9,]+) \(')
HASM = re.compile(r'^\s*-\s*\[(0x[0-9A-Fa-f]+),\s*hasm(?:,\s*([^\]]+?))?\]\s*(?:#\s*(.*))?$', re.MULTILINE)


def managed_assembly(root: Path):
    segments = []
    for path in sorted((root / "yamls").rglob("*.yaml")):
        for address, name, comment in HASM.findall(path.read_text(encoding="utf-8")):
            label = (name or comment or "managed assembly").strip()
            segments.append((path.relative_to(root).as_posix(), address, label))
    return segments

def render(root: Path, baseline: Path) -> str:
    existing = baseline.read_text(encoding="utf-8")
    total_match = TOTAL.search(existing)
    if not total_match:
        raise SystemExit("coverage total missing from baseline")
    total = int(total_match.group(1).replace(",", ""))
    owners = {}
    for path in sorted((root / "src").rglob("*.c")):
        functions = PRAGMA.findall(path.read_text(encoding="utf-8"))
        if functions:
            owners[path.relative_to(root).as_posix()] = functions
    remaining = sum(len(functions) for functions in owners.values()); covered = total - remaining
    managed = managed_assembly(root)
    lines = [
        "<!-- Generated by ci/update_coverage.py. Do not edit by hand. -->", "",
        "# pokestadium decompilation coverage", "", "<!-- AUTO_COVERAGE:START -->",
        f"- Functions with C implementations: **{covered:,} / {total:,} ({covered / total * 100:.1f}%)**",
        f"- Remaining decompilable `GLOBAL_ASM` owners: **{remaining:,}** (across {len(owners):,} source files)",
        f"- Separately managed `hasm` assembly segments: **{len(managed):,}**",
        "<!-- AUTO_COVERAGE:END -->", "",
        "The function denominator covers C source owners and `GLOBAL_ASM` stubs. `hasm` entries are deliberately managed assembly segments, not unported C-function owners, so they are reported separately and excluded from the decompilation backlog. Total function count is derived from the retail linker map and retained from the trusted baseline. Regenerate with:",
        "`python3 ci/update_coverage.py`", "", "## Remaining owners by source file", "",
        "| File | Remaining owners | Functions |", "| --- | ---: | --- |",
    ]
    lines += [
        f"| `{path}` | {len(functions)} | {', '.join(f'`{name}`' for name in functions)} |"
        for path, functions in owners.items()
    ]
    lines += ["", "## Separately managed assembly segments", "", "These YAML `hasm` entries are kept as assembly by design and are not counted as `GLOBAL_ASM` decompilation candidates.", "", "| YAML | ROM offset | Segment |", "| --- | ---: | --- |"]
    lines += [f"| `{path}` | `{address}` | `{label}` |" for path, address, label in managed]
    return "\n".join(lines) + "\n"

def main():
    parser = argparse.ArgumentParser(); parser.add_argument("--repo-root", type=Path, default=Path.cwd()); parser.add_argument("--baseline", type=Path); parser.add_argument("--output", type=Path); parser.add_argument("--check", action="store_true")
    args = parser.parse_args(); root = args.repo_root.resolve(); output = args.output or root / "COVERAGE.md"; text = render(root, args.baseline or root / "COVERAGE.md")
    if args.check: return 0 if output.exists() and output.read_text(encoding="utf-8") == text else 1
    output.write_text(text, encoding="utf-8")
    return 0
if __name__ == "__main__": raise SystemExit(main())
