#!/usr/bin/env python3
"""Refresh Stadium 1 coverage from tracked GLOBAL_ASM pragmas.

The total function count is the retail-map value recorded in COVERAGE.md; this
script never executes PR code or requires a ROM.
"""
import argparse
import re
from pathlib import Path

PRAGMA = re.compile(r'#pragma GLOBAL_ASM\("asm/us/nonmatchings/[^" ]+/[^"/]+\.s"\)')
TOTAL = re.compile(r'\*\*[0-9,]+ / ([0-9,]+) \(')

def render(root: Path, baseline: Path) -> str:
    existing = baseline.read_text(encoding="utf-8")
    total_match = TOTAL.search(existing)
    if not total_match:
        raise SystemExit("coverage total missing from baseline")
    total = int(total_match.group(1).replace(",", ""))
    owners = {}
    for path in sorted((root / "src").rglob("*.c")):
        count = len(PRAGMA.findall(path.read_text(encoding="utf-8")))
        if count:
            owners[path.relative_to(root).as_posix()] = count
    remaining = sum(owners.values()); covered = total - remaining
    lines = [
        "<!-- Generated by ci/update_coverage.py. Do not edit by hand. -->", "",
        "# pokestadium decompilation coverage", "", "<!-- AUTO_COVERAGE:START -->",
        f"- Functions with C implementations: **{covered:,} / {total:,} ({covered / total * 100:.1f}%)**",
        f"- Remaining `GLOBAL_ASM` owners: **{remaining:,}** (across {len(owners):,} source files)",
        "<!-- AUTO_COVERAGE:END -->", "",
        "Total function count is derived from the retail linker map and retained from the trusted baseline. Regenerate with:",
        "`python3 ci/update_coverage.py`", "", "## Remaining owners by source file", "",
        "| File | Remaining owners |", "| --- | ---: |",
    ]
    lines += [f"| `{path}` | {count} |" for path, count in owners.items()]
    return "\n".join(lines) + "\n"

def main():
    parser = argparse.ArgumentParser(); parser.add_argument("--repo-root", type=Path, default=Path.cwd()); parser.add_argument("--baseline", type=Path); parser.add_argument("--output", type=Path); parser.add_argument("--check", action="store_true")
    args = parser.parse_args(); root = args.repo_root.resolve(); output = args.output or root / "COVERAGE.md"; text = render(root, args.baseline or root / "COVERAGE.md")
    if args.check: return 0 if output.exists() and output.read_text(encoding="utf-8") == text else 1
    output.write_text(text, encoding="utf-8")
    return 0
if __name__ == "__main__": raise SystemExit(main())
