#!/usr/bin/env python3
"""Generate COVERAGE.md for pokestadium.

Adapted from the sibling GS repo's tools/update_coverage.py, but pokestadium
has no tracked historical baseline to anchor a total against (its
asm/us/nonmatchings/*.s stubs are gitignored, unlike GS's force-tracked
ones), so the total function count here comes from the current linker map
instead: every .text symbol whose object file is under build/src/ -- since
a still-GLOBAL_ASM function's assembled bytes end up in that same object
file's .text section as a matched one's would, this counts both regardless
of match status in one pass, no separate historical snapshot needed.

Usage: python3 tools/update_coverage.py [--repo-root PATH] [--map PATH] [--output PATH]
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

PRAGMA_RE = re.compile(r'GLOBAL_ASM\("asm/us/nonmatchings/([^" ]+)/([^"/]+)\.s"\)')
SECTION_HEADER_RE = re.compile(r'^\s*\.text\s+0x[0-9a-fA-F]+\s+0x[0-9a-fA-F]+\s+(\S+)\s*$')
OTHER_SECTION_RE = re.compile(r'^\s*\.(data|rodata|bss|sdata|sbss|late_rodata)\b')
SYMBOL_LINE_RE = re.compile(r'^\s+0x([0-9a-fA-F]+)\s+([A-Za-z_][A-Za-z0-9_]*)\s*$')
START_MARKER = "<!-- AUTO_COVERAGE:START -->"
END_MARKER = "<!-- AUTO_COVERAGE:END -->"
GENERATED_HEADER = "<!-- Generated by tools/update_coverage.py. Do not edit by hand. -->"


def remaining_owners_by_file(repo_root: Path) -> dict[str, set[str]]:
    """{source_path: {owner_names}} for every #pragma GLOBAL_ASM stub still in src/**.c."""
    result = subprocess.run(
        ["git", "-C", str(repo_root), "grep", "--no-color", "-E",
         r'GLOBAL_ASM\("asm/us/nonmatchings/[^" ]+/[^"/]+\.s"\)', "--", "src"],
        check=False, capture_output=True, text=True,
    )
    if result.returncode not in (0, 1):
        raise RuntimeError(result.stderr.strip() or f"git grep failed: {result.returncode}")
    owners: dict[str, set[str]] = {}
    for line in result.stdout.splitlines():
        path, sep, content = line.partition(":")
        if not sep:
            continue
        match = PRAGMA_RE.search(content)
        if not match:
            continue
        owners.setdefault(path, set()).add(match.group(2))
    return owners


def total_functions_from_map(map_path: Path, object_prefix: str = "build/src/") -> int | None:
    """Count .text symbols whose object file is under object_prefix.

    Best-effort: a still-GLOBAL_ASM function's assembled instructions land
    in the very same object file's .text section as a matched function's
    would (both are just contributions to that translation unit's object),
    so this counts every function this project's own source owns -- matched
    or not -- without needing a historical zero-progress snapshot. Returns
    None if map_path does not exist (no build has been done yet).
    """
    if not map_path.is_file():
        return None
    in_src_text = False
    names: set[str] = set()
    with map_path.open(encoding="utf-8", errors="replace") as fh:
        for line in fh:
            header = SECTION_HEADER_RE.match(line)
            if header:
                in_src_text = header.group(1).startswith(object_prefix)
                continue
            if OTHER_SECTION_RE.match(line):
                in_src_text = False
                continue
            if line.startswith("build/") and "(" in line:
                # e.g. "build/src/foo.o(.data)" -- a new object/section entry
                # without its own .text ADDR SIZE line means we've left .text.
                if "(.text)" not in line:
                    in_src_text = False
                continue
            if in_src_text:
                sym = SYMBOL_LINE_RE.match(line)
                if sym:
                    names.add(sym.group(2))
    return len(names)


def render_file_table(remaining_by_file: dict[str, int]) -> str:
    if not remaining_by_file:
        return "_No source files with remaining `GLOBAL_ASM` owners._"
    lines = ["| File | Remaining owners |", "| --- | ---: |"]
    for path in sorted(remaining_by_file):
        lines.append(f"| `{path}` | {remaining_by_file[path]:,} |")
    return "\n".join(lines)


def render_coverage_md(remaining_by_file: dict[str, int], total: int | None) -> str:
    remaining = sum(remaining_by_file.values())
    lines = [GENERATED_HEADER, "", "# pokestadium decompilation coverage", "", START_MARKER]
    if total is not None:
        covered = max(total - remaining, 0)
        pct = (covered / total * 100.0) if total else 0.0
        lines.append(f"- Functions with C implementations: **{covered:,} / {total:,} ({pct:.1f}%)**")
    lines.append(f"- Remaining `GLOBAL_ASM` owners: **{remaining:,}** (across {len(remaining_by_file)} source files)")
    if total is None:
        lines.append(
            "- Total function count unavailable (no `build/pokestadium-us.map` on disk -- "
            "run `make extract && make -j` once, then regenerate this file)"
        )
    lines += [
        END_MARKER,
        "",
        "Total function count is derived from the current linker map's `.text` symbols "
        "under `build/src/`, not a historical zero-progress snapshot (unlike the sibling "
        "GS repo's `COVERAGE.md`, pokestadium's `asm/us/nonmatchings/*.s` stubs are "
        "gitignored, so no such snapshot exists to anchor to) -- it naturally includes "
        "both matched and still-`GLOBAL_ASM` functions, since either way their bytes end "
        "up in that same object file's `.text` section. Regenerate with:\n"
        "`python3 tools/update_coverage.py`",
        "",
        "## Remaining owners by source file",
        "",
        render_file_table(remaining_by_file),
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", type=Path, default=None)
    parser.add_argument("--map", type=Path, default=None)
    parser.add_argument("--output", type=Path, default=None)
    args = parser.parse_args()

    repo_root = (args.repo_root or Path(__file__).resolve().parent.parent).resolve()
    map_path = args.map or (repo_root / "build" / "pokestadium-us.map")
    output = args.output or (repo_root / "COVERAGE.md")

    remaining_by_file = remaining_owners_by_file(repo_root)
    remaining_counts = {path: len(names) for path, names in remaining_by_file.items()}
    total = total_functions_from_map(map_path)

    content = render_coverage_md(remaining_counts, total)
    output.write_text(content, encoding="utf-8")

    remaining = sum(remaining_counts.values())
    if total is not None:
        covered = max(total - remaining, 0)
        print(f"coverage: {covered}/{total} ({covered/total*100:.1f}%), {remaining} GLOBAL_ASM remaining [{output}]")
    else:
        print(f"coverage: total unknown (no map), {remaining} GLOBAL_ASM remaining [{output}]")
    return 0


if __name__ == "__main__":
    sys.exit(main())
